name: mobile_1
description: A new Flutter project.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  
  provider: ^5.0.0
  barcode_widget: ^2.0.1
  cached_network_image: ^3.0.0
  http: ^0.13.2
  blurrycontainer: ^0.0.1
  flutter_svg: ^0.22.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  video_player: ^2.1.6
  sensors_plus: ^2.0.2
  flutter_sensors: ^1.0.1
  geolocator: ^9.0.2
  location: ^4.4.0
  flutter_local_notifications: ^13.0.0
  google_maps_flutter: ^2.2.5
  geocoding: ^2.1.0
  latlong: ^0.6.1
 
  flutter_map: ^3.1.0
  
  audioplayers: ^0.19.1
  
  

dev_dependencies:
 
  flutter_test:
    sdk: flutter
  flutter_polyline_points: ^1.0.0
  url_launcher: ^6.1.5
  awesome_icons: ^1.1.0
  font_awesome_flutter: ^10.1.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/data/data.json
    - assets/images/
    - assets/videos/1.mp4
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

    
    
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

    
   
    
