name: mobile_1
description: A new Flutter project.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  video_player: ^2.1.6
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  url_launcher: ^6.1.5
  awesome_icons: ^1.1.0
  font_awesome_flutter: ^10.1.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/1.mp4
    
